### ISSUE TITLE
Training on custom data

### ISSUE THREAD

**Issue by chiran7** [sandipan211/ZSD-SC-Resolver#11]
Dear @sandipan211 ,

I have one more query. I got good results for MSCOCO data. Now, I want to train in custom data. In the training steps, for MSCOCO, MSCOCO/fasttext.npy is required, and Pascal VOC also requires /workspace/arijit_ug/sushil/zsd/VOC/fasttext_synonym.npy is required in step 4 and step 5.

Is this file created during training from steps 1-3? If so, similar .npy files for class embeddings may be created for custom data. I may then be able to train steps 4 and step 5 for complete training in custom data.

Thank you for your time and consideration.

**Comment by sandipan211** [comment]
These files for semantic embeddings are not generated in the steps mentioned in README. We had taken them from another GitHub repo for previous work on ZSD. Kindly see my reply to issue #4 for more details.

**Comment by chiran7** [comment]
Dear @sandipan211 ,

I have one query regarding class embedding. In the current repository, for MSCOCO, MSCOCO/fasttext.npy, it uses 81*300 dimensional embedding , and Pascal VOC, VOC/fasttext_synonym.npy, it uses 21*300 dimensional embedding. It may be because 81th in coco and 21st in voc may represent background class.
I want to create similar class embedding for custom data having 50 different number of classes. In that case, is the class embedding (for instance, in VOC/fasttext_synonym.npy) that can represent different categorical name of classes into numerical representation? Is using the python embedding function , such as word2vec , is only to represent the different classes with names in string to numerical value with 300 dimensions for each class ?

The class embedding weight (such as fasttext.npy) is required to train the regressor, specially in step 3.

Thank you for your time and consideration.
