### ISSUE TITLE
Custom Data

### ISSUE THREAD

**Issue by saintour** [sandipan211/ZSD-SC-Resolver#13]
What steps should I take if I want to train with custom data? Thanks in advance.

**Comment by sandipan211** [comment]
Hi @saintour ,

I have not trained myself with custom datasets, but I have tested my trained model on random images taken from the internet. However, if you want to train on custom data, these are the things to keep in mind:

1. The first step would be to make your dataset compatible with the COCO format. A tutorial on how you can make a customized COCO format dataset can be found [here](https://mmdetection.readthedocs.io/en/dev-3.x/advanced_guides/customize_dataset.html). 
2. Then, you have to define a seen-unseen split for the classes of that dataset. Suppose you have that list of S seen and U unseen classes. Define them in [splits.py](https://github.com/sandipan211/ZSD-SC-Resolver/blob/main/mmdetection/splits.py). Make the appropriate changes while loading the data and semantics for these classes.
3. [This](https://github.com/sandipan211/ZSD-SC-Resolver/blob/5fb34dc8bec81617ab030dceaae650ebd7e2c900/mmdetection/mmdet/datasets/custom.py) file encloses the class for a custom dataset. Make the necessary changes in [this](file). It contains the config parameters. While running any script, you must use this config file from now on. 
4. Train a CNN backbone of your choice (like Resnet-101) on Imagenet classes **after removing any class from Imagenet that exists in U**. **This is strictly as per zero-shot criteria**, but if you wish, you can omit this step and directly use the one we [provide](https://drive.google.com/file/d/1wAgWbceKwS6c_zjZ3KzkDm7SNoKQOynJ/view).

That's it! Now you can follow the steps 1-6 given in the README.
