### ISSUE TITLE
is train_unseen_classifier.py missing

### ISSUE THREAD

**Issue by twangnh** [sandipan211/ZSD-SC-Resolver#16]
@sandipan211 Hi, thanks for sharing the code, but train_unseen_classifier.py is not found, is it missing ?

**Comment by sandipan211** [comment]
Hi @twangnh , 

You probably found this mention about train_unseen_classifier.py in the runner.sh/voc_runner.sh files, **but that was not ultimately used for our framework**. I have removed that unnecessary line from those shell files now. 

Kindly follow our README.md to reproduce our results. All the required files, logs and codes are given.
