### ISSUE TITLE
how to generate test npy for unseen classes

### ISSUE THREAD

**Issue by twangnh** [sandipan211/ZSD-SC-Resolver#17]
Hi @sandipan211 , thanks for sharing the great work! i tired transfering the code to custom dataset, but in the generattor training step, it shows test_xxx.npy is not found, how to generate the file?

**Comment by sandipan211** [comment]
Kindly refer to this [previous reply](https://github.com/sandipan211/ZSD-SC-Resolver/issues/3#issuecomment-1366721036)

**Comment by twangnh** [comment]
thanks!
