### ISSUE TITLE
custom dataset tune

### ISSUE THREAD

**Issue by twangnh** [sandipan211/ZSD-SC-Resolver#18]
Hi @sandipan211 thanks for sharing the work and having timely reply for issues! we are recenly using the code for training a custom dataset, with about 10 seen classes and 5 unseen classes, could you please give some suggestions on tuning the hyper-pararmeters in this code, as we observe there are a lot of hyper-parameters and we don't how to tune them best for a new dataset.

Thanks!

**Comment by sandipan211** [comment]
Hi @twangnh ,
I have uploaded the definitions for the hyperparameters [here](https://github.com/sandipan211/ZSD-SC-Resolver/blob/main/script/hyperparams.md). Hope it helps!

**Comment by twangnh** [comment]
thanks!
