### ISSUE TITLE
Can you provide some output files？

### ISSUE THREAD

**Issue by aaaaxxc** [sandipan211/ZSD-SC-Resolver#21]
Can you provide the output files of these two code segments, including VOC and COCO?
python tools/zero_shot_utils.py configs/faster_rcnn_r101_fpn_1x.py --classes seen --load_from ./work_dirs/coco2014/epoch_12.pth --save_dir ./data --data_split train
python tools/zero_shot_utils.py configs/faster_rcnn_r101_fpn_1x.py --classes unseen --load_from ./work_dirs/coco2014/epoch_12.pth --save_dir ./data --data_split test

**Comment by sandipan211** [comment]
Hi @aaaaxxc ,

As far as I remember, the extracted features are stored as numpy files. But I'm not currently at the university, so I don't have access to those output files. I can upload them by Monday. Meanwhile, can you tell me what's the issue you are facing in running zero_shot_utils.py?

**Comment by aaaaxxc** [comment]
Hello!
I saw that in another issue you implemented the code in a higher version of torch, but mmdet and mmcv are still giving the error "undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E". This seems to be a problem with the CUDA version being too high (CUDA 11.1, which is the minimum version my graphics card can support). [https://github.com/yrcong/STTran/issues/51] I tried to solve this issue by upgrading the versions of mmdet (2.28.2) and mmcv (1.7.2), but mmdet 2.x is not compatible with the models and pre-trained models of mmdet 1.x.
Moreover, the machines that I can use which support lower versions of CUDA have smaller memory, and the memory is insufficient when running COCO code. Therefore, my machine cannot simultaneously meet the requirements of supporting a lower version of CUDA and having high memory.
At the same time, I am also unsure whether different features will affect the final results. In several generative codes I have run, the VOC results seem to differ slightly from those in the paper.

**Comment by sandipan211** [comment]
Ah, I see. Yeah, these version incompatibilities can be seriously frustrating. Well then I can upload the files on Monday.

**Comment by aaaaxxc** [comment]
Hi Sandipan Sarma,

I hope this message finds you well.

I am writing to follow up on the request we discussed earlier. I had reached out to you for assistance, and I greatly appreciate your initial response. However, I have not yet received the requested materials that were to be provided by the agreed-upon date.

I understand that you may be busy, but I wanted to gently remind you about this matter. Your help is crucial, and I would be grateful if you could provide the information at your earliest convenience.

Thank you again for your assistance and understanding.

Best regards,
Xu Xingchen

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, May 25, 2024 01:25 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [sandipan211/ZSD-SC-Resolver] Can you provide some output files？ (Issue #21)

&nbsp;



 
Ah, I see. Yeah, these version incompatibilities can be seriously frustrating. Well then I can upload the files on Monday.

**Comment by sandipan211** [comment]
@aaaaxxc  Sorry for the delay. Due to some unforeseen circumstances, I reached my institute today. [Here](https://mega.nz/folder/bRMmBI6Z#5UTGcTrP0v4yOaEfgRmc1g) are the extracted train and test features for the PASCAL VOC dataset. Unfortunately, I do not have enough cloud storage for uploading the features of COCO dataset, since it is 35 GB in size. 

See if this will be enough for you. You're welcome to suggest any alternate way of sending large files over the internet if you want the COCO features as well.

**Comment by aaaaxxc** [comment]
Thank you for your help. I resolved the issue after adding 128GB of memory.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, May 29, 2024 10:05 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [sandipan211/ZSD-SC-Resolver] Can you provide some output files？ (Issue #21)

&nbsp;



 
@aaaaxxc  Sorry for the delay. Due to some unforeseen circumstances, I reached my institute today. Here are the extracted train and test features for the PASCAL VOC dataset. Unfortunately, I do not have enough cloud storage for uploading the features of COCO dataset, since it is 35 GB in size.
 
See if this will be enough for you. You're welcome to suggest any alternate way of sending large files over the internet if you want the COCO features as well.

**Comment by sandipan211** [comment]
Good to know that!


Regards
Sandipan Sarma

Research Scholar,
Dept. of Computer Science and Engineering,
Indian Institute of Technology (IIT) Guwahati,
Assam, India.
________________________________
