### ISSUE TITLE
Author， Do you think you will update the code and environment to the latest version？

### ISSUE THREAD

**Issue by lichong0** [sandipan211/ZSD-SC-Resolver#22]
@sandipan211 There are many problems when I try to reproduce the environment. The code should be old. I want to know whether the author can reconstruct the code on the newer mmcv and torch

**Comment by sandipan211** [comment]
@lichong0 unfortunately, I am not going to be able to reproduce the environment on the newer version in the near future. For the time being, at best, you can see some of my answers to the closed issues raised by others - many of them were able to solve the issues.

**Comment by lichong0** [comment]
Thanks
