### ISSUE TITLE
I have some questions about training on VOC datasets

### ISSUE THREAD

**Issue by lichong0** [sandipan211/ZSD-SC-Resolver#23]
During the training and testing processes of a generative model（The fifth step and the sixth step）. Do both the `val` and `test` sets in the VOC dataset configs file need to be set to 'seen' or unseen ? 
 val=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/val.txt',
        img_prefix=data_root + 'VOC2007/',
        classes_to_load='seen',
        split=split,
        pipeline=test_pipeline),
test=dict(
        type=dataset_type,
        ann_file=data_root + 'VOC2007/ImageSets/Main/test.txt',
        img_prefix=data_root + 'VOC2007/',
        split=split,
        classes_to_load='seen',
        pipeline=test_pipeline))

**Comment by sandipan211** [comment]
In case of VOC, follow [this](https://github.com/sandipan211/ZSD-SC-Resolver/blob/main/mmdetection/configs/pascal_voc/faster_rcnn_r101_fpn_1x_voc0712.py) config file. Both should be seen. It has been a while since I uploaded the codes, and I don't exactly remember why we kept them like this. Maybe we have hardcoded something in some intermediate file. But it is correct.

**Comment by lichong0** [comment]
When to set unsee categories，test？

**Comment by lichong0** [comment]
> In case of VOC, follow [this](https://github.com/sandipan211/ZSD-SC-Resolver/blob/main/mmdetection/configs/pascal_voc/faster_rcnn_r101_fpn_1x_voc0712.py) config file. Both should be seen. It has been a while since I uploaded the codes, and I don't exactly remember why we kept them like this. Maybe we have hardcoded something in some intermediate file. But it is correct.

Are the settings the same for ZSD and GZSD?

**Comment by sandipan211** [comment]
> When to set unsee categories，test？

In case of VOC especially, just keep it exactly the same as mentioned in [this](https://github.com/sandipan211/ZSD-SC-Resolver/blob/main/mmdetection/configs/pascal_voc/faster_rcnn_r101_fpn_1x_voc0712.py) file.

**Comment by sandipan211** [comment]
> > In case of VOC, follow [this](https://github.com/sandipan211/ZSD-SC-Resolver/blob/main/mmdetection/configs/pascal_voc/faster_rcnn_r101_fpn_1x_voc0712.py) config file. Both should be seen. It has been a while since I uploaded the codes, and I don't exactly remember why we kept them like this. Maybe we have hardcoded something in some intermediate file. But it is correct.
> 
> Are the settings the same for ZSD and GZSD?

For VOC dataset, ZSD/GZSD setting was ill-defined when we did this work. If you look at our paper, for VOC, we have just shown seen and unseen class results - nothing explicitly defined as ZSD/GZSD as in MSCOCO.

To summarize, for VOC we just did one experiment following previous works - just find the results separately on seen and unseen classes and report them. And that experiment shall be done following our command in step 6, replacing with voc related weight files and config files. 

Please use the "zsd" flag for evaluation on VOC.

**Comment by lichong0** [comment]
File "tools/test.py", line 263, in <module>
    main()
  File "tools/test.py", line 245, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "tools/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=not show, **data)
  File "G:\anaconda\envs\zsod_py36pt11\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "G:\anaconda\envs\zsod_py36pt11\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "G:\anaconda\envs\zsod_py36pt11\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "e:\lichong\rrfs\mmdetection\mmdet\core\fp16\decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "e:\lichong\rrfs\mmdetection\mmdet\models\detectors\faster_rcnn.py", line 73, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "e:\lichong\rrfs\mmdetection\mmdet\models\detectors\base.py", line 102, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "e:\lichong\rrfs\mmdetection\mmdet\models\detectors\two_stage.py", line 274, in simple_test
    x, img_meta, proposal_list, self.test_cfg.rcnn, rescale=rescale)
  File "e:\lichong\rrfs\mmdetection\mmdet\models\detectors\test_mixins.py", line 118, in simple_test_bboxes
    cls_score, bbox_pred = self.test_zsd(rcnn_test_cfg, cls_score, bbox_pred)
  File "e:\lichong\rrfs\mmdetection\mmdet\models\detectors\test_mixins.py", line 57, in test_zsd
    bbox_pred[ii, ar+(unseen[ii]*4) ] = bbox_pred[ii, ar+(seen[ii]*4) ]
IndexError: tensors used as indices must be long, byte or bool tensors
