### ISSUE TITLE
Do you still have the weight file obtained by executing the fifth step

### ISSUE THREAD

**Issue by GuangyuanLiu1999** [sandipan211/ZSD-SC-Resolver#6]
Hello sir, do you still have the weight file obtained by executing the fifth step ./script/train_coco_generator_65_15.sh? I have been unable to reproduce your results when all settings and parameters have not been changed, and the mAP difference is %14 from yours in the GZSD settings, and other parameters are also quite different from yours. I hope you can tell more details or you can share the result file.
		        recall		        mAP
ZSD		        64.3 (65.1)	        18.5 (20.1)
GZSD   seen	63.1 (58.6)	        24.1 (37.4)
	  unseen	30.2 (64.0)	        15.6 (20.1)
The results provided in your paper are in brackets.

**Comment by sandipan211** [comment]
I have provided the output of the training as .pth files. Kindly see the evaluation step in README.md.

**Comment by GuangyuanLiu1999** [comment]
> I have provided the output of the training as .pth files. Kindly see the evaluation step in README.md.

Thank you for your reply, very much appreciated!
